// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/about-page/Current.tsx": () => import("../components/mockups/about-page/Current.tsx"),
  "./components/mockups/about-page/Draft.tsx": () => import("../components/mockups/about-page/Draft.tsx")
};
